### ISSUE TITLE
Cannot open html  that begin with underscore in github pages

### ISSUE THREAD

**Issue by meteor199** [TypeStrong/typedoc-site#4]
![image](https://user-images.githubusercontent.com/21106029/33110982-77ecaaca-cf86-11e7-9692-5c0be27bddd6.png)
https://github.com/TypeStrong/typedoc/issues/620

**Comment by aciccarello** [comment]
Oops, I think the `.nojekyll` needs to be in the root. I guess we'll have to use the `include` directive.

https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/

**Comment by aciccarello** [comment]
I'm having some trouble getting this fixed as I haven't used Jekyll before and I can't get Jekyll running on Windows to get things working. Any help would be appreciated.

**Comment by WasabiFan** [comment]
I've done some minor sleuthing in Jekyll internals before (because it's frustratingly flimsy) so I saw this and figured I'd give it a shot... long story short, it looks like there's a bug in Jekyll (or at least, the version this repo locks to). It seems to have mangled paths during globbing so that it checks the filters against nonexistent paths such as `D:/path/to/typedoc-site/_assert_.html`. Note the missing `api/` path segment. The `include` filter in `_config.yml` isn't catching the files because the `api/` portion of the path is being stripped.

Setting the include filter to just be `*.html` fixes it locally for me (on Windows, at least). It's suboptimal but I don't think there are any issues it'll cause in this repo.

For future reference, problem is visible here: https://github.com/jekyll/jekyll/blob/53cfa642fb50379b8795f80622bf9a5b934f2729/lib/jekyll/entry_filter.rb#L90
Likely originates here somewhere: https://github.com/jekyll/jekyll/blob/53cfa642fb50379b8795f80622bf9a5b934f2729/lib/jekyll/collection.rb#L74 

I despise Ruby with a fiery passion so I'm not inclined to go further :laughing: I could open an issue on the Jekyll repo but they might not be happy that it isn't tested with the latest version (which I'm having issues installing locally).

Hope that helps!

**Comment by aciccarello** [comment]
@WasabiFan :heart: Thank you so much. That seems to work well enough. I appreciate you sharing the lessons of your explorations :sweat_smile:

**Comment by WasabiFan** [comment]
🎉 Glad to hear it! As much as I like Jekyll at the macro level, its implementation sure can be annoying... _especially_ as a windows user.
